#
#    ICRAR - International Centre for Radio Astronomy Research
#    (c) UWA - The University of Western Australia
#    Copyright by UWA (in the framework of the ICRAR)
#    All rights reserved
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
#    MA 02111-1307  USA
#
# Create a Docker container for running Java

FROM centos:latest

RUN yum update -y
RUN yum -y install \
    git \
    wget

ENV JAVA_VERSION 8u66
ENV BUILD_VERSION b17

# Downloading Java
# http://download.oracle.com/otn-pub/java/jdk/8u66-b17/jdk-8u66-linux-x64.rpm?AuthParam=1452473767_f67c638617dbf11e1e2b0060bfd1910b
RUN wget --quiet --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/$JAVA_VERSION-$BUILD_VERSION/jdk-$JAVA_VERSION-linux-x64.rpm" -O /tmp/jdk-8-linux-x64.rpm

RUN yum -y install /tmp/jdk-8-linux-x64.rpm

RUN alternatives --install /usr/bin/java jar /usr/java/latest/bin/java 200000
RUN alternatives --install /usr/bin/javaws javaws /usr/java/latest/bin/javaws 200000
RUN alternatives --install /usr/bin/javac javac /usr/java/latest/bin/javac 200000

ENV JAVA_HOME /usr/java/latest

RUN mkdir -p /opt/chiles02
WORKDIR /opt/chiles02
RUN git clone https://github.com/ICRAR/aws-chiles02.git

# Docker uses a clever caching system that won't get the latest code
# unless you do an explicit pull
WORKDIR /opt/chiles02/aws-chiles02
RUN git pull

# Copy the scripts
COPY scripts /opt/chiles02/scripts/

# Make them executable
RUN chmod oug+x /opt/chiles02/scripts/*.sh

# Update the path
env PATH /opt/chiles02/scripts:$PATH
env PYTHONPATH $PYTHONPATH:/opt/chiles02/aws-chiles02/pipeline

VOLUME /dfms_root
