#!/bin/sh
#PBS -N pbs-generate-statistics
#PBS -l nodes=1:ppn=2:compute,walltime=48:00:00
#PBS -t 1-4937
#PBS -q usmall
# usmall is 32 items on the queue usmall2 is 8
#PBS -j oe

cd /home/kevin/aws-chiles02/machine_learning/casa_code
export PYTHONPATH=/home/kevin/aws-chiles02/machine_learning
/mnt/science1/kevin/casa-release-4.7.2-el6/bin/casa --nologger --log2term -c generate_statistics.py 13b-266 uvsub_deep_2017_05_25 ${PBS_ARRAYID} --settings_file_name /home/kevin/aws-chiles02/machine_learning/casa_code/scan.settings
