#cloud-config
package_upgrade: all

# Install additional packages on first boot
packages:
  - htop
  - sysstat
  - iotop

# Write the boto and docker files if needed
write_files:
% if type == 'node manager':
  - path: "/etc/sysconfig/docker"
    permissions: "0644"
    owner: "root"
    content: |
      # The max number of open files for the daemon itself, and all
      # running containers.  The default value of 1048576 mirrors the value
      # used by the systemd service unit.
      DAEMON_MAXFILES=1048576

      # Additional startup options for the Docker daemon, for example:
      # OPTIONS="--ip-forward=true --iptables=true"
      # By default we limit the number of open files per container
      OPTIONS="-D --default-ulimit nofile=16384:16384"
  - path: "/etc/sysconfig/docker-storage-setup"
    permissions: "0544"
    owner: "root"
    content: |
      VG=daliuge-group
      DATA_SIZE=100GB
% endif
  - path: "/root/.aws/credentials"
    permissions: "0544"
    owner: "root"
    content: |
      [${profile}]
      aws_access_key_id = ${aws_access_key_id}
      aws_secret_access_key = ${aws_secret_access_key}
  - path: "/home/ec2-user/.aws/credentials"
    permissions: "0544"
    owner: "ec2-user:ec2-user"
    content: |
      [${profile}]
      aws_access_key_id = ${aws_access_key_id}
      aws_secret_access_key = ${aws_secret_access_key}

# Final_message written to log when cloud-init processes are finished
final_message: "System boot (via cloud-init) is COMPLETE, after $UPTIME seconds. Finished at $TIMESTAMP"
