name: aws-chiles02
dependencies:
  - python=3.8
  - boto3
  - ConfigObj
  - cython
  - jsonpickle
  - jupyter
  - mako
  - pip
  - requests
  - ruamel.yaml
  - six
  - pip:
    - daliuge
    - markuppy
