name: aws-chiles02
dependencies:
  - python=3.7
  - boto3
  - ConfigObj
  - cython
  - jupyter
  - mako
  - pip
  - requests
  - six
  - pip:
    - daliuge
    - jsonpickle
    - markuppy
    - ruamel.yaml
