#!/bin/sh
#PBS -N pbs-copy_makecube_input_pleiades
#PBS -l nodes=1:ppn=1:compute,walltime=24:00:00
#PBS -t 0-120
#PBS -q usmall2
# usmall is 32 items on the queue usmall2 is 8
#PBS -j oe
cd ~

module load python
module load openssl

source /home/kevin/virt_env/chiles_pipeline/bin/activate
/home/kevin/virt_env/chiles_pipeline/bin/python /home/kevin/chiles_pipeline/python/copy_makecube_input_pleiades.py pbs ${PBS_ARRAYID}
